rotation on bedaura
zPeanut/Hydrogen pull request #27
Opened 2021-07-22 14:07 UTC by ProfKambing

i tried to add the setrotationyaw but its kinda retarded

2021-07-22 15:55 UTC, Morten-Renner commented
I haven't tested it yet. But it seems fine so far.

---
A potential issue might be the following.
Sending an additional packet could lead to an AC kick/ban due to packet spam. For some ACs we're already very close to the maximum.

Or it cloud interfere when a player hits an entity at the same time. For the server it would look like the player is looking at the bed and hitting an entity at a different direction. In my experience more ACs react to this than breaking a bed without looking at it.

Sending the PlayerLook packet should at least be optional. A Setting for it would be good.

2021-07-22 17:17 UTC, Morten-Renner commented
Also please make sure next time that you commit with the default line seperators. We use CRLF the Windows default. Thats why git shows that every line changed.

2021-07-22 17:29 UTC, Morten-Renner requested changes
1. Please add a Setting for this feature, make it optional.
2. Please commit the file with CRLF line breaks.

2021-07-23 01:13 UTC, ProfKambing commented
okay

2021-07-23 01:13 UTC, ProfKambing commented
i could make it use yawrotation instead of packet

2021-07-27 15:26 UTC, zPeanut commented
make it toggable and ill merge

2021-07-27 15:26 UTC, zPeanut commented
also use yawrotation

2021-07-27 23:19 UTC, ProfKambing commented
okay

2021-08-06 13:44 UTC, closed without merging